trigger:
- BranchInit

# Use self-hosted agent pool (ensure you have self-hosted agents set up)
pool:
  name: Selfhost # Replace 'Default' with your self-hosted agent pool name if you have one.

# Define jobs or steps that can be optimized for parallel execution
jobs:
- job: BuildAndDeploy
  displayName: 'Build and Deploy Job'
  
  # You can split the job into multiple steps or use conditionals if needed
  steps:
  - script: echo Hello, world!
    displayName: 'Run a one-line script'

  - script: |
      echo Add other tasks to build, test, and deploy your project.
      echo See https://aka.ms/yaml
    displayName: 'Run a multi-line script'
